name: 'Label PR'
description: 'Label a PR'
inputs:
  hasOneOf:
    description: 'Label that needs to be added to each PR'
    required: false
  githubToken:
    description: 'The Github access token for PR API'
    required: true
outputs:
  passed:
    description: 'Pull request has passed required label check'
runs: 
  using: 'node12'
  main: 'index.js'
branding:
  color: purple
  icon: anchor


