on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  do-not-merge-check:
    if: github.base_ref == 'master' || github.base_ref == 'main'
    runs-on: ubuntu-latest
    name: Workflow to block PR merge if the said PR is not labeled
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Checkout
    - uses: ./
    - id: checkPRLabel
    - name: Check PR label
      with:
        hasOneOf: production ready, production blocked
        githubToken: ${{ secrets.GITHUB_TOKEN }}
