on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  do-not-merge-check:
    if: github.base_ref == 'master' || github.base_ref == 'main'
    runs-on: ubuntu-latest
    name: A job block PR merge if the said PR is not labeled
    steps:
    - name: Check for PR label
      id: checkPRLabel
      uses: actions/sample-github-action@v1.2
      with:
        hasOneOf: production ready, production blocked
        githubToken: ${{ secrets.GITHUB_TOKEN }}
