on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  do-not-merge-check:
    if: github.base_ref == 'master' || github.base_ref == 'main'
    runs-on: ubuntu-latest
    name: Workflow to block PR merge if the said PR is not labeled
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Check PR label
      id: checkPRLabel
      uses: ./
      with:
        hasOneOf: production ready,production blocked
        githubToken: ${{ secrets.GITHUB_TOKEN }}
